/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author paulo
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttPalpite = new javax.swing.JButton();
        lblFalaGenio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spnPalpite = new javax.swing.JSpinner();
        lblImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttPalpite.setText("Palpite");
        bttPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(bttPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 100, 50));

        lblFalaGenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFalaGenio.setText("<html>Vou pensar em um<br>valor entre 1 e 5<br>Tente Adivinhar</html>");
        getContentPane().add(lblFalaGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 160, 80));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, -1));

        spnPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 170, 80, 40));

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genio.jpg"))); // NOI18N
        lblImage1.setText("jLabel4");
        getContentPane().add(lblImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 200, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPalpiteActionPerformed
        int valor = (int) spnPalpite.getValue();
        int pensamentoGenio = (int)(Math.random()* 5)+1;
        lblFalaGenio.setText(valor == pensamentoGenio ? "Acertou":"<html>ERROU!<br>eu pensei no valor " + pensamentoGenio + "</html>");
    }//GEN-LAST:event_bttPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFalaGenio;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JSpinner spnPalpite;
    // End of variables declaration//GEN-END:variables
}
